Repository yetanotherco/aligned_layer, pull requests merged in 2024-09, with the labels that each got.

#869 feat (batcher): allow users to specify max fee
  batcher/Cargo.lock
  batcher/aligned-batcher/Cargo.toml
  batcher/aligned-batcher/src/eth/mod.rs
  batcher/aligned-batcher/src/lib.rs
  batcher/aligned-batcher/src/types/batch_queue.rs
  batcher/aligned-batcher/src/types/errors.rs
  batcher/aligned-sdk/abi/BatcherPaymentService.json
  batcher/aligned-sdk/src/communication/messaging.rs
  batcher/aligned-sdk/src/core/errors.rs
  batcher/aligned-sdk/src/core/types.rs
  batcher/aligned-sdk/src/eth/batcher_payment_service.rs
  batcher/aligned-sdk/src/sdk.rs
  batcher/aligned/src/main.rs
  contracts/bindings/AlignedLayerServiceManager/binding.go
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/src/core/BatcherPaymentService.sol
  docs/3_guides/1.2_SDK_api_reference.md
Labels: audit, due-diligence

#910 feat: add limit on aggregator spending
  .github/workflows/build-rust.yml
  aggregator/internal/pkg/aggregator.go
  batcher/aligned-batcher/src/eth/mod.rs
  batcher/aligned-batcher/src/lib.rs
  batcher/aligned-sdk/abi/AlignedLayerServiceManager.json
  batcher/aligned-sdk/abi/BatcherPaymentService.json
  batcher/aligned-sdk/src/eth/aligned_service_manager.rs
  contracts/bindings/AlignedLayerServiceManager/binding.go
  contracts/scripts/anvil/deploy_aligned_contracts.sh
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/src/core/AlignedLayerServiceManager.sol
  contracts/src/core/AlignedLayerServiceManagerStorage.sol
  contracts/src/core/BatcherPaymentService.sol
  contracts/src/core/IAlignedLayerServiceManager.sol
  contracts/test/AlignedLayerServiceManager.t.sol
  core/chainio/avs_subscriber.go
  core/chainio/avs_writer.go
  explorer/lib/abi/AlignedLayerServiceManager.json
  explorer/lib/abi/BatcherPaymentService.json
  explorer/lib/explorer/contract_managers/aligned_layer_service_manager.ex
  explorer/lib/explorer/models/batch_structs.ex
  explorer/lib/explorer/models/batches.ex
  explorer/lib/explorer_web/live/pages/batch/index.html.heex
  explorer/priv/repo/migrations/20240830171448_add_max_aggregator_fee_to_batches.exs
  operator/pkg/operator.go
Labels: audit, due-diligence

#879 feat(explorer): add operator version via tracker api
  docs/3_guides/6_setup_aligned.md
  explorer/.env.dev
  explorer/.env.example
  explorer/config/config.exs
  explorer/lib/abi/AlignedLayerServiceManager.json
  explorer/lib/explorer/contract_managers/aligned_layer_service_manager.ex
  explorer/lib/explorer/models/restakings.ex
  explorer/lib/explorer_web/components/assets_cta.ex
  explorer/lib/explorer_web/components/core_components.ex
  explorer/lib/explorer_web/components/nav.ex
  explorer/lib/explorer_web/live/pages/batch/index.html.heex
  explorer/lib/explorer_web/live/pages/batches/index.html.heex
  explorer/lib/explorer_web/live/pages/operator/index.ex
  explorer/lib/explorer_web/live/pages/operators/index.ex
  explorer/lib/explorer_web/live/pages/restakes/index.ex
  explorer/lib/explorer_web/live/pages/search/index.ex
  explorer/lib/explorer_web/live/releases_helper.ex
  explorer/lib/explorer_web/live/tracker.ex
  explorer/start.sh
Labels: frontend

#1041 fix: build `hashStruct` following EIP description and do not perform keccak on `nonce` and `maxFee`
  batcher/aligned-sdk/src/core/types.rs
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/scripts/anvil/state/eigenlayer-deployed-anvil-state.json
  contracts/src/core/BatcherPaymentService.sol
Labels: audit, batcher, sdk

#1008 refactor(batcher): batch building algorithm
  batcher/aligned-batcher/src/lib.rs
  batcher/aligned-batcher/src/types/batch_queue.rs
  batcher/aligned-batcher/src/types/errors.rs
  batcher/aligned-sdk/src/sdk.rs
  explorer/mix.lock
Labels: refactor

#1085 feat(audit): Use block timestamp instead of block number.
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/src/core/BatcherPaymentService.sol
  contracts/src/core/BatcherPaymentServiceStorage.sol
Labels: audit

#1094 fix(contracts): check address are not zero in initialization
  Makefile
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/src/core/AlignedLayerServiceManager.sol
  contracts/src/core/BatcherPaymentService.sol
  contracts/src/core/IAlignedLayerServiceManager.sol
  contracts/test/AlignedLayerServiceManager.t.sol
Labels: audit, fuzzing-labs
