Repository yetanotherco/aligned_layer, pull requests merged in 2024-10, with the labels that each got.

#1088 fix: operator double signature
  aggregator/internal/pkg/aggregator.go
  aggregator/internal/pkg/server.go
  core/chainio/avs_reader.go
  core/chainio/avs_writer.go
  core/chainio/bindings.go
  core/config/base.go
  core/utils/eth_client_utils.go
  go.mod
  go.sum
  operator/cmd/actions/deposit_into_strategy.go
  operator/pkg/register.go
Labels: audit, least-authority

#1106 refactor(batcher): add user state & other code quality refactors
  batcher/Cargo.lock
  batcher/aligned-batcher/src/connection.rs
  batcher/aligned-batcher/src/lib.rs
  batcher/aligned-batcher/src/types/batch_queue.rs
  batcher/aligned-batcher/src/types/batch_state.rs
  batcher/aligned-batcher/src/types/errors.rs
  batcher/aligned-batcher/src/types/mod.rs
  batcher/aligned-batcher/src/types/user_state.rs
  batcher/aligned-sdk/src/communication/messaging.rs
  batcher/aligned-sdk/src/core/errors.rs
  batcher/aligned-sdk/src/core/types.rs
  batcher/aligned/send_burst_tasks.sh
Labels: audit, least-authority, refactor

#1073 fix: operator downtime
  .gitignore
  config-files/config-operator-1.yaml
  config-files/config-operator-2.yaml
  config-files/config-operator-3.yaml
  config-files/config-operator.yaml
  config-files/config.yaml
  core/chainio/avs_reader.go
  core/chainio/avs_subscriber.go
  core/config/operator.go
  operator/pkg/operator.go
Labels: audit, fuzzing-labs

#1004 fix(audit): Remove Task data from aggregator after a response has been responded or expires.
  aggregator/cmd/main.go
  aggregator/internal/pkg/aggregator.go
  batcher/Cargo.lock
  config-files/config-aggregator.yaml
  core/chainio/avs_reader.go
  core/config/aggregator.go
Labels: audit
