Repository yetanotherco/aligned_layer, pull requests merged in 2024-06, with the labels that each got.

#254 Improve FFI build in Makefile
  Makefile
  README.md
Labels: in-review

#279 feat(explorer): add tx link and block to etherscan and other misc changes and improvements
  README.md
  explorer/.env.dev
  explorer/.env.example
  explorer/config/runtime.exs
  explorer/lib/explorer_web/components/core_components.ex
  explorer/lib/explorer_web/components/layouts/app.html.heex
  explorer/lib/explorer_web/components/layouts/root.html.heex
  explorer/lib/explorer_web/live/pages/batch/index.html.heex
  explorer/lib/explorer_web/live/pages/batches/index.html.heex
  explorer/lib/explorer_web/live/pages/home/index.ex
  explorer/lib/explorer_web/live/pages/home/index.html.heex
Labels: frontend

#280 feat: readme batcher cli simplify sending proofs process by using cargo install
  Makefile
  README.md
Labels: in-review

#270 feat: add infinite sp1 for testnet
  Makefile
  batcher/client/send_infinite_sp1_tasks/generate_address.py
  batcher/client/send_infinite_sp1_tasks/requirements.txt
  batcher/client/send_infinite_sp1_tasks/send_infinite_sp1_tasks.sh
Labels: in-review

#244 fix(batcher): send correct responses to each client
  Makefile
  batcher/client/src/main.rs
  batcher/src/eth/mod.rs
  batcher/src/lib.rs
  batcher/src/main.rs
  batcher/src/types/batch_queue.rs
  batcher/src/types/mod.rs
  config-files/config.yaml
Labels: in-review

#339 feat(explorer): add batch status on detail page
  explorer/lib/explorer_web/components/core_components.ex
  explorer/lib/explorer_web/live/pages/batch/index.html.heex
  explorer/lib/explorer_web/live/pages/batches/index.html.heex
Labels: frontend, in-review

#316 feat(batcher): send response to clients once task has been confirmed in ethereum
  batcher/Cargo.lock
  batcher/client/Cargo.lock
  batcher/client/src/main.rs
  batcher/src/eth/mod.rs
  batcher/src/lib.rs
  batcher/src/main.rs
  batcher/src/types/errors.rs
  batcher/src/types/mod.rs
Labels: in-review

#357 fix: change groth make target in readme
  README.md
Labels: in-review

#203 feat: add upgrade script for contracts
  Makefile
  README.md
  contracts/script/upgrade/AlignedLayerUpgrader.s.sol
  contracts/script/upgrade/RegistryCoordinatorUpgrader.s.sol
  contracts/scripts/anvil/upgrade_aligned_contracts.sh
  contracts/scripts/anvil/upgrade_registry_coordinator.sh
  contracts/scripts/upgrade_aligned_contracts.sh
  contracts/scripts/upgrade_registry_coordinator.sh
Labels: in-review

#367 feat(batcher client): add verify function in service manager to check proof merkle path
  .gitignore
  Makefile
  README.md
  batcher/Cargo.lock
  batcher/aligned-batcher-lib/Cargo.toml
  batcher/aligned-batcher-lib/src/types/mod.rs
  batcher/aligned-batcher/src/eth/abi/AlignedLayerServiceManager.json
  batcher/aligned-batcher/src/eth/mod.rs
  batcher/aligned-batcher/src/gnark/mod.rs
  batcher/aligned-batcher/src/halo2/ipa/mod.rs
  batcher/aligned-batcher/src/halo2/kzg/mod.rs
  batcher/aligned/Cargo.toml
  batcher/aligned/abi/AlignedLayerServiceManager.json
  batcher/aligned/generate_proof_and_send.sh
  batcher/aligned/src/errors.rs
  batcher/aligned/src/eth.rs
  batcher/aligned/src/main.rs
  batcher/openzeppelin_merkle_tree/.tool-versions
  batcher/openzeppelin_merkle_tree/merkle_tree.js
  batcher/openzeppelin_merkle_tree/package-lock.json
  batcher/openzeppelin_merkle_tree/package.json
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/src/core/AlignedLayerServiceManager.sol
Labels: in-review

#427 client-side verification data commitments calculation and response verification
  batcher/aligned-batcher-lib/src/types/mod.rs
  batcher/aligned-batcher/src/lib.rs
  batcher/aligned/src/main.rs
  batcher/aligned/src/types.rs
Labels: in-review

#457 fix(explorer): improve table responsiveness on mobile
  explorer/assets/js/app.js
  explorer/lib/explorer_web/components/core_components.ex
  explorer/lib/explorer_web/components/dark_mode.ex
  explorer/lib/explorer_web/components/layouts/app.html.heex
  explorer/lib/explorer_web/components/layouts/root.html.heex
  explorer/lib/explorer_web/live/pages/batches/index.html.heex
  explorer/lib/explorer_web/live/pages/home/index.ex
  explorer/priv/static/images/hero.jpeg
  explorer/priv/static/images/og-image.webp
  explorer/priv/static/robots.txt
Labels: frontend

#476 fix: add error handling for bad rpc connection
  explorer/lib/explorer_web/live/pages/home/index.ex
Labels: in-review

#449 feat: first version of payment system
  Makefile
  config-files/anvil.aggregator.bls.key.json
  config-files/anvil.aggregator.ecdsa.key.json
  config-files/config-aggregator.yaml
  contracts/script/deploy/AlignedLayerDeployer.s.sol
  contracts/script/upgrade/AlignedLayerUpgrader.s.sol
  contracts/script/upgrade/RegistryCoordinatorUpgrader.s.sol
  contracts/scripts/anvil/state/alignedlayer-deployed-anvil-state.json
  contracts/scripts/anvil/state/eigenlayer-deployed-anvil-state.json
  contracts/src/core/AlignedLayerServiceManager.sol
  contracts/src/core/AlignedLayerServiceManagerStorage.sol
  contracts/test/AlignedLayerServiceManager.t.sol
  scripts/fund_batcher_balance_in_aligned_devnet.sh
Labels: in-review

#497 fix(explorer): add real time updates
  explorer/lib/explorer/models/batches.ex
  explorer/lib/explorer/periodically.ex
  explorer/lib/explorer_web/live/pages/batch/index.ex
  explorer/lib/explorer_web/live/pages/batches/index.ex
  explorer/lib/explorer_web/live/pages/home/index.ex
Labels: frontend

#471 feat: batcher client message signing
  README_SEND_PROOFS.md
  batcher/Cargo.lock
  batcher/aligned-batcher-lib/Cargo.toml
  batcher/aligned-batcher-lib/src/types/mod.rs
  batcher/aligned-batcher/src/lib.rs
  batcher/aligned-batcher/src/types/errors.rs
  batcher/aligned/Cargo.toml
  batcher/aligned/src/errors.rs
  batcher/aligned/src/main.rs
Labels: in-review
